In [ ]:
from bcb import sgs
import plotly.express as px

ipca = sgs.get({"IPCA":433},start='2024-01-31').reset_index()
#ipca["Ano"] = ipca["Date"].dt.year
#media_anual = ipca.groupby('Ano')["IPCA"].sum().reset_index(name="Media IPCA Anual")
ipca["mes"] = ipca["Date"].dt
ipca
# fig_line = px.line(
#     media_anual,
#     x='Ano',
#     y='Media IPCA Anual',
#     template="plotly_dark",
#     title="Evolução do IPCA Médio Anual"
# )

# fig_line.show()

         Date  IPCA  mes
0  2024-01-01  0.42    1
1  2024-02-01  0.83    2
2  2024-03-01  0.16    3
3  2024-04-01  0.38    4
4  2024-05-01  0.46    5
5  2024-06-01  0.21    6
6  2024-07-01  0.38    7
7  2024-08-01 -0.02    8
8  2024-09-01  0.44    9
9  2024-10-01  0.56   10
10 2024-11-01  0.39   11
11 2024-12-01  0.52   12
12 2025-01-01  0.16    1
13 2025-02-01  1.31    2
14 2025-03-01  0.56    3
15 2025-04-01  0.43    4
16 2025-05-01  0.26    5
17 2025-06-01  0.24    6

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup

driver = webdriver.Chrome()

driver.maximize_window()

driver.get("https://www.freitasleiloeiro.com.br/Home/Index")

lista_carros = driver.find_element(By.ID,"dvDestaquesVeiculos0")


print(lista_carros)

NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=139.0.7258.66)
Stacktrace:
	GetHandleVerifier [0x0x7ff72ffc6b55+79621]
	GetHandleVerifier [0x0x7ff72ffc6bb0+79712]
	(No symbol) [0x0x7ff72fd5c0ea]
	(No symbol) [0x0x7ff72fd34601]
	(No symbol) [0x0x7ff72fde25fe]
	(No symbol) [0x0x7ff72fe02d02]
	(No symbol) [0x0x7ff72fddaf13]
	(No symbol) [0x0x7ff72fda4151]
	(No symbol) [0x0x7ff72fda4ee3]
	GetHandleVerifier [0x0x7ff73028686d+2962461]
	GetHandleVerifier [0x0x7ff730280b8d+2938685]
	GetHandleVerifier [0x0x7ff73029f74d+3064573]
	GetHandleVerifier [0x0x7ff72ffe0c9e+186446]
	GetHandleVerifier [0x0x7ff72ffe8a6f+218655]
	GetHandleVerifier [0x0x7ff72ffcf944+115956]
	GetHandleVerifier [0x0x7ff72ffcfaf9+116393]
	GetHandleVerifier [0x0x7ff72ffb5f28+10968]
	BaseThreadInitThunk [0x0x7ff928cae8d7+23]
	RtlUserThreadStart [0x0x7ff92aefc34c+44]

In [ ]:
from bs4 import BeautifulSoup
from selenium import webdriver
import time
from datetime import datetime
import pywhatkit as kit
import pandas as pd

def enviar_mensagem(mensagem,telefone):

    try:
        # Envia a mensagem imediatamente
        kit.sendwhatmsg_instantly(phone_no=telefone, message=mensagem, wait_time=15)
        print(f"Mensagem enviada para {telefone}")
    except Exception as e:
        print(f"Erro ao enviar mensagem: {e}")

def monitorar_preços():

    driver = webdriver.Chrome()

    url ='https://leilo.com.br/leilao/carros?'

    driver.get(url)

    time.sleep(11)

    home = BeautifulSoup(driver.page_source, 'html.parser')

    lista_lotes = home.find_all('div',class_='col-llg-2 col-lg-3 col-md-4 col-sm-4 col-xs-6')

    todos_carros = []

    # Extrair múltiplos itens
    for lote in lista_lotes:

        modelo = lote.find("h3",class_="q-ma-none text-weight-600 text-secondary").text
        ano = lote.find('p',class_='text-ano text-grey-8 q-mb-none').text
        km = lote.find("p",class_="text-km text-grey-8 q-mb-none").text
        preço = lote.find("li",class_='valor-atual').text
        carro = {"Carro":modelo,
                "Ano":ano,
                "Kilometragem":km,
                "Preço":preço}
        
        todos_carros.append(carro)

    driver.quit()

    def limpar_dados(valor):
        return valor.replace("\n","").replace('\xa0','').strip()
    
    dados_limpos = []

    for carro in cars:
        dados_limpos.append({
            'Carros': cars['Carro'],
            'Ano':limpar_dados(cars['Ano'].replace(",",'')),
            'Kilometragem': limpar_dados(cars['Kilometragem']),
            "Preço": limpar_dados(cars['Preço'])
        })

    df_car = pd.DataFrame(dados_limpos, columns=['Carros','Ano','Kilometragem','Preço'])

    return df_car

# intervalo_minutos = 60 # verificar a cada hora
# telefone = "+5561991484015"

# carros = monitorar_preços()

# mensagem = f"🚨ALERTA DE CARROS🚨 {carros}"

# enviar_mensagem(mensagem,telefone)

In [42]:
monitorar_preços()

                     Carros                    Ano Kilometragem        Preço
0  FIAT/BRAVO SPORTING (4P)  13                /14   103.097 km  R$24.000,00
1  FIAT/BRAVO SPORTING (4P)  13                /14   103.097 km  R$24.000,00
2  FIAT/BRAVO SPORTING (4P)  13                /14   103.097 km  R$24.000,00
3  FIAT/BRAVO SPORTING (4P)  13                /14   103.097 km  R$24.000,00

In [ ]:
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
from datetime import datetime
import pywhatkit as kit  # Para envio pelo WhatsApp

def enviar_whatsapp(mensagem, telefone):
    """Envia mensagem para um número no WhatsApp"""
    try:
        # Envia a mensagem imediatamente
        kit.sendwhatmsg_instantly(phone_no=telefone, message=mensagem, wait_time=15)
        print(f"Mensagem enviada para {telefone}")
    except Exception as e:
        print(f"Erro ao enviar mensagem: {e}")

def monitorar_leiloes():
    driver = webdriver.Chrome()
    url = 'https://leilo.com.br/leilao/carros?'
    
    try:
        driver.get(url)
        
        # Espera explícita para carregar os elementos
        WebDriverWait(driver, 20).until(
            EC.presence_of_element_located((By.CLASS_NAME, "q-px-sm-sm"))
        )
        
        home = BeautifulSoup(driver.page_source, 'html.parser')
        
        # Lista para armazenar carros que atendem aos critérios
        carros_interessantes = []
        
        for lote in home.find_all('div', class_="q-px-sm-sm q-px-xs q-pb-sm"):
            try:
                carro = lote.find('div', class_="header-card q-mt-sm cursor-pointer relative-position").text.strip()
                preco_element = lote.find('div', class_="current-bid")
                preco = preco_element.text.strip() if preco_element else "Preço não disponível"
                
                print(f"Carro: {carro} | Preço: {preco}")

                        
            except Exception as e:
                print(f"Erro ao processar lote: {e}")
                continue
        
        # Se encontrou carros interessantes, envia alerta
        if carros_interessantes:
            mensagem = "🚨 ALERTA DE PREÇOS BAIXOS 🚨\n\n"
            mensagem += f"Encontrados {len(carros_interessantes)} carros com preços interessantes:\n\n"
            
            for idx, (carro, preco) in enumerate(carros_interessantes, 1):
                mensagem += f"{idx}. {carro} - {preco}\n"
            
            mensagem += f"\nVerifique: {url}\n\n{datetime.now().strftime('%d/%m/%Y %H:%M')}"
            
            # Envia para o WhatsApp (substitua pelo número desejado)
            telefone = "+5561991484015"  # Substitua pelo número com código do país
            enviar_whatsapp(mensagem, telefone)
            
    finally:
        driver.quit()
    
    return carros_interessantes

# Configuração do monitoramento periódico
intervalo_minutos = 60  # Verifica a cada hora (ajuste conforme necessário)

while True:
    print(f"\nIniciando verificação em {datetime.now().strftime('%d/%m/%Y %H:%M')}")
    resultados = monitorar_leiloes()
    
    if resultados:
        print(f"Encontrados {len(resultados)} carros com preços interessantes!")
    else:
        print("Nenhum carro com preço abaixo do limite encontrado.")
    
    print(f"Próxima verificação em {intervalo_minutos} minutos...")
    time.sleep(intervalo_minutos * 60)  # Converte minutos para segundos

Iniciando verificação em 09/08/2025 22:44
Carro: Recuperado de FinanciamentoHONDA/CG 160 FANfavorite_bordercalendar_today
                20
                /20137.169 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoFIAT/MOBI EASY ON (4P)favorite_bordercalendar_today
                16
                /1782.046 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoFORD/ECOSPORT FREESTYLE ATfavorite_bordercalendar_today
                14
                /15151.733 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoRENAULT/DUSTER EXPRESSION SCEfavorite_bordercalendar_today
                19
                /2094.874 km
                Lance enviado por B**********0 Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoCHEVROLET/CELTA LT 1.0L (2P/4P)favorite_bordercalendar_today
                12
                /1388.126 km
                Lance enviado por M*********S Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoRENAULT/SANDERO EXPRESSION (4P)favorite_bordercalendar_today
                14
                /15246.430 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoFORD/FIESTA FLEX (4P)favorite_bordercalendar_today
                12
                /13121.329 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoCHEVROLET/TRAILBLAZER LTZ D4Afavorite_bordercalendar_today
                17
                /18215.659 km Lance atual | Preço: Preço não disponível
Carro: LEILOSHOPFIAT/MOBI LIKE (4P)favorite_bordercalendar_today
                22
                /2345.797 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoVOLKSWAGEN/NOVO GOL (2P/4P)favorite_bordercalendar_today
                12
                /13151.716 km
                Lance enviado por J***8 Lance atual | Preço: Preço não disponível
Carro: LEILOSHOPMITSUBISHI/L200 TRITON SPORT GLfavorite_bordercalendar_today
                21
                /2223.699 km
                Lance enviado por L******E Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoCHEVROLET/ONIX  LTZ 1.4 AUTOMATICO (4P)favorite_bordercalendar_today
                13
                /14109.692 km
                Lance enviado por L********O Lance atual | Preço: Preço não disponível
Carro: LEILOSHOPBMW/X5 XDRIVE 35Ifavorite_bordercalendar_today
                14
                /14181.435 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoFIAT/UNO ATTRACTIVE (4P/2P)favorite_bordercalendar_today
                20
                /21217.894 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoDAF/XF 105 FTS 480favorite_bordercalendar_today
                21
                /22277.553 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoFORD/ECOSPORT SE ATfavorite_bordercalendar_today
                12
                /13219.976 km Lance atual | Preço: Preço não disponível
Carro: LEILOSHOPVOLKSWAGEN/GOL 1.0 GIV (2P/4P)favorite_bordercalendar_today
                13
                /1416.010 km
                Lance enviado por R********0 Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoHYUNDAI/SANTA FEfavorite_bordercalendar_today
                10
                /11154.920 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoRENAULT/MEGANE DYNAMIQUE (4P)favorite_bordercalendar_today
                07
                /08196.901 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoFORD/FUSION (4P)favorite_bordercalendar_today
                07
                /0749.804 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoPEUGEOT/207 XR SPORT (2P/4P)favorite_bordercalendar_today
                11
                /12186.925 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoTOYOTA/COROLLA XEI FLEX (4P)favorite_bordercalendar_today
                11
                /11232.393 km
                Lance enviado por T*****X Lance atual | Preço: Preço não disponível
Carro: LEILOSHOPCHEVROLET/ONIX 10MT LT1favorite_bordercalendar_today
                22
                /2362.554 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoAUDI/A3 LIMOUSINE (4P)favorite_bordercalendar_today
                15
                /1678.836 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoHONDA XRE 300favorite_bordercalendar_today
                17
                /173.968 km Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoCHEVROLET/MONTANA LS2favorite_bordercalendar_today
                17
                /18189.847 km Lance atual | Preço: Preço não disponível
Carro: LEILOSHOPVOLKSWAGEN/SPACEFOXfavorite_bordercalendar_today
                08
                /08301.723 km Lance atual | Preço: Preço não disponível
Carro: LEILOSHOPVOLKSWAGEN/PASSAT TURBO (4P)favorite_bordercalendar_today
                11
                /11160.091 km
                Lance enviado por m****o Lance atual | Preço: Preço não disponível
Carro: Recuperado de FinanciamentoPEUGEOT/207 PASSION XR (4P)favorite_bordercalendar_today
                11
                /12149.832 km Lance atual | Preço: Preço não disponível
Carro: LEILOSHOPMERCEDES-BENZ/CLA-45 AMG 4MATIC (4P)favorite_bordercalendar_today
                16
                /17115.131 km Lance atual | Preço: Preço não disponível
Nenhum carro com preço abaixo do limite encontrado.
Próxima verificação em 60 minutos...

In [ ]:
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
from datetime import datetime

def monitorar_leiloes():
    driver = webdriver.Chrome()
    url = 'https://leilo.com.br/leilao/carros?'
    
    try:
        print("Acessando o site...")
        driver.get(url)
        
        # Espera explícita para carregar os elementos
        WebDriverWait(driver, 20).until(
            EC.presence_of_element_located((By.CLASS_NAME, "q-px-sm-sm"))
        )
        
        home = BeautifulSoup(driver.page_source, 'html.parser')
        
        print("\nResultados encontrados:")
        print("-" * 50)
        
        for lote in home.find_all('div', class_="q-px-sm-sm q-px-xs q-pb-sm"):
            try:
                # Extrai informações do carro
                carro = lote.find('div', class_="header-card q-mt-sm cursor-pointer relative-position")
                nome_carro = carro.text.strip() if carro else "Nome não disponível"
                
                # Extrai preço - ajuste a classe conforme necessário
                preco_element = lote.find('div', class_="current-bid")
                preco = preco_element.text.strip() if preco_element else "Preço não disponível"
                
                # Extrai outras informações relevantes (ajuste conforme necessário)
                lance_minimo = lote.find('div', class_="min-bid")
                lance_min = lance_minimo.text.strip() if lance_minimo else "Lance mínimo não disponível"
                
                print(f"Carro: {nome_carro}")
                print(f"Preço atual: {preco}")
                print(f"Lance mínimo: {lance_min}")
                print("-" * 50)
                
            except Exception as e:
                print(f"Erro ao processar um lote: {e}")
                continue
        
    finally:
        driver.quit()

# Configuração do monitoramento periódico
intervalo_minutos = 60  # Verifica a cada hora (ajuste conforme necessário)

while True:
    print(f"\nIniciando verificação em {datetime.now().strftime('%d/%m/%Y %H:%M')}")
    monitorar_leiloes()
    
    print(f"Próxima verificação em {intervalo_minutos} minutos...")
    time.sleep(intervalo_minutos * 60)  # Converte minutos para segundos

Iniciando verificação em 09/08/2025 22:46
Acessando o site...

Resultados encontrados:
--------------------------------------------------
Carro: Recuperado de FinanciamentoHONDA/CG 160 FANfavorite_bordercalendar_today
                20
                /20137.169 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoFIAT/MOBI EASY ON (4P)favorite_bordercalendar_today
                16
                /1782.046 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoFORD/ECOSPORT FREESTYLE ATfavorite_bordercalendar_today
                14
                /15151.733 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoRENAULT/DUSTER EXPRESSION SCEfavorite_bordercalendar_today
                19
                /2094.874 km
                Lance enviado por B**********0 Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoCHEVROLET/CELTA LT 1.0L (2P/4P)favorite_bordercalendar_today
                12
                /1388.126 km
                Lance enviado por M*********S Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoRENAULT/SANDERO EXPRESSION (4P)favorite_bordercalendar_today
                14
                /15246.430 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoFORD/FIESTA FLEX (4P)favorite_bordercalendar_today
                12
                /13121.329 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoCHEVROLET/TRAILBLAZER LTZ D4Afavorite_bordercalendar_today
                17
                /18215.659 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: LEILOSHOPFIAT/MOBI LIKE (4P)favorite_bordercalendar_today
                22
                /2345.797 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoVOLKSWAGEN/NOVO GOL (2P/4P)favorite_bordercalendar_today
                12
                /13151.716 km
                Lance enviado por J***8 Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: LEILOSHOPMITSUBISHI/L200 TRITON SPORT GLfavorite_bordercalendar_today
                21
                /2223.699 km
                Lance enviado por L******E Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoCHEVROLET/ONIX  LTZ 1.4 AUTOMATICO (4P)favorite_bordercalendar_today
                13
                /14109.692 km
                Lance enviado por L********O Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: LEILOSHOPBMW/X5 XDRIVE 35Ifavorite_bordercalendar_today
                14
                /14181.435 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoFIAT/UNO ATTRACTIVE (4P/2P)favorite_bordercalendar_today
                20
                /21217.894 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoDAF/XF 105 FTS 480favorite_bordercalendar_today
                21
                /22277.553 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoFORD/ECOSPORT SE ATfavorite_bordercalendar_today
                12
                /13219.976 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: LEILOSHOPVOLKSWAGEN/GOL 1.0 GIV (2P/4P)favorite_bordercalendar_today
                13
                /1416.010 km
                Lance enviado por R********0 Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoHYUNDAI/SANTA FEfavorite_bordercalendar_today
                10
                /11154.920 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoRENAULT/MEGANE DYNAMIQUE (4P)favorite_bordercalendar_today
                07
                /08196.901 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoFORD/FUSION (4P)favorite_bordercalendar_today
                07
                /0749.804 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoPEUGEOT/207 XR SPORT (2P/4P)favorite_bordercalendar_today
                11
                /12186.925 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoTOYOTA/COROLLA XEI FLEX (4P)favorite_bordercalendar_today
                11
                /11232.393 km
                Lance enviado por T*****X Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: LEILOSHOPCHEVROLET/ONIX 10MT LT1favorite_bordercalendar_today
                22
                /2362.554 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoAUDI/A3 LIMOUSINE (4P)favorite_bordercalendar_today
                15
                /1678.836 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoHONDA XRE 300favorite_bordercalendar_today
                17
                /173.968 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoCHEVROLET/MONTANA LS2favorite_bordercalendar_today
                17
                /18189.847 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: LEILOSHOPVOLKSWAGEN/SPACEFOXfavorite_bordercalendar_today
                08
                /08301.723 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: LEILOSHOPVOLKSWAGEN/PASSAT TURBO (4P)favorite_bordercalendar_today
                11
                /11160.091 km
                Lance enviado por m****o Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: Recuperado de FinanciamentoPEUGEOT/207 PASSION XR (4P)favorite_bordercalendar_today
                11
                /12149.832 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Carro: LEILOSHOPMERCEDES-BENZ/CLA-45 AMG 4MATIC (4P)favorite_bordercalendar_today
                16
                /17115.131 km Lance atual
Preço atual: Preço não disponível
Lance mínimo: Lance mínimo não disponível
--------------------------------------------------
Próxima verificação em 60 minutos...

In [43]:
def monitorar_preços():
    driver = webdriver.Chrome()
    url = 'https://leilo.com.br/leilao/carros?'
    driver.get(url)
    time.sleep(11)
    
    home = BeautifulSoup(driver.page_source, 'html.parser')
    lista_lotes = home.find_all('div', class_="q-px-sm-sm q-px-xs q-pb-sm")
    
    todos_carros = []  # Lista para armazenar todos os carros coletados
    
    # Extrair múltiplos itens
    for lote in lista_lotes:
        try:
            modelo = lote.find("h3", class_="q-ma-none text-weight-600 text-secondary").text
            ano = lote.find('p', class_='text-ano text-grey-8 q-mb-none').text
            km = lote.find("p", class_="text-km text-grey-8 q-mb-none").text
            preço = lote.find("li", class_='valor-atual').text
            
            carro = {
                "Carro": modelo,
                "Ano": ano,
                "Kilometragem": km,
                "Preço": preço
            }
            todos_carros.append(carro)
        except Exception as e:
            print(f"Erro ao processar um lote: {e}")
            continue
    
    driver.quit()  # Não esqueça de fechar o driver
    
    # Função para limpar os dados
    def limpar_dados(valor):
        return valor.replace("\n", "").replace('\xa0', '').strip()
    
    # Processar todos os carros coletados
    dados_limpos = []
    for carro in todos_carros:
        dados_limpos.append({
            'Carro': limpar_dados(carro['Carro']),
            'Ano': limpar_dados(carro['Ano']),
            'Kilometragem': limpar_dados(carro['Kilometragem']),
            'Preço': limpar_dados(carro['Preço'])
        })
    
    df_car = pd.DataFrame(dados_limpos)
    return df_car

In [45]:
dataframe = monitorar_preços()

dataframe

,Carro,Ano,Kilometragem,Preço
0,FIAT/MOBI EASY ON (4P),16 /17,82.046 km,"R$22.600,00"
1,FORD/ECOSPORT FREESTYLE AT,14 /15,151.733 km,"R$30.000,00"
2,RENAULT/DUSTER EXPRESSION SCE,19 /20,94.874 km,"R$38.800,00"
3,CHEVROLET/CELTA LT 1.0L (2P/4P),12 /13,88.126 km,"R$15.600,00"
4,RENAULT/SANDERO EXPRESSION (4P),14 /15,246.430 km,"R$19.000,00"
5,FORD/FIESTA FLEX (4P),12 /13,121.329 km,"R$12.000,00"
6,CHEVROLET/TRAILBLAZER LTZ D4A,17 /18,215.659 km,"R$86.000,00"
7,FIAT/MOBI LIKE (4P),22 /23,45.797 km,"R$34.000,00"
8,VOLKSWAGEN/NOVO GOL (2P/4P),12 /13,151.716 km,"R$18.200,00"
9,MITSUBISHI/L200 TRITON SPORT GL,21 /22,23.699 km,"R$93.000,00"
10,CHEVROLET/ONIX LTZ 1.4 AUTOMATICO (4P),13 /14,109.692 km,"R$28.400,00"
11,FIAT/UNO ATTRACTIVE (4P/2P),20 /21,217.894 km,"R$26.000,00"
12,FORD/ECOSPORT SE AT,12 /13,219.976 km,"R$28.300,00"
13,VOLKSWAGEN/GOL 1.0 GIV (2P/4P),13 /14,16.010 km,"R$10.600,00"
14,HYUNDAI/SANTA FE,10 /11,154.920 km,"R$28.000,00"
15,RENAULT/MEGANE DYNAMIQUE (4P),07 /08,196.901 km,"R$10.500,00"
16,FORD/FUSION (4P),07 /07,49.804 km,"R$15.700,00"
17,PEUGEOT/207 XR SPORT (2P/4P),11 /12,186.925 km,"R$12.300,00"
18,TOYOTA/COROLLA XEI FLEX (4P),11 /11,232.393 km,"R$37.200,00"
19,CHEVROLET/ONIX 10MT LT1,22 /23,62.554 km,"R$38.500,00"
20,AUDI/A3 LIMOUSINE (4P),15 /16,78.836 km,"R$60.500,00"
21,CHEVROLET/MONTANA LS2,17 /18,189.847 km,"R$27.800,00"
22,VOLKSWAGEN/SPACEFOX,08 /08,301.723 km,"R$6.600,00"
23,VOLKSWAGEN/PASSAT TURBO (4P),11 /11,160.091 km,"R$33.000,00"
24,PEUGEOT/207 PASSION XR (4P),11 /12,149.832 km,"R$11.500,00"
25,MERCEDES-BENZ/CLA-45 AMG 4MATIC (4P),16 /17,115.131 km,"R$129.000,00"
26,RENAULT/KWID ZEN 1.0 MECANICO (4P),17 /18,116.598 km,"R$20.700,00"
27,VOLKSWAGEN/NOVO GOL TRENDLINE MBV (4P/2P),16 /17,109.740 km,"R$29.600,00"
28,VOLKSWAGEN/POLO COMFORTLINE AB (4P),23 /23,45.223 km,"R$62.500,00"
29,FIAT/BRAVO SPORTING (4P),13 /14,103.097 km,"R$24.000,00"

In [46]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Carro         30 non-null     object
 1   Ano           30 non-null     object
 2   Kilometragem  30 non-null     object
 3   Preço         30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB